### ISSUE TITLE
Introduction.mdown misspelling

### ISSUE THREAD

**Issue by evxn** [Farata/EnterpriseWebBook#2]
Subsection "From DHTML to HTML5"
paragraph 6 
The word "frameworks" is ommited.

**Comment by gAmUssA** [comment]
Could you submit pull request?
Thanks

**Comment by evxn** [comment]
Yes, sure.

**Comment by gAmUssA** [comment]
merged pull request wit commit eefcd36ae1e21a2d57328dc0d51ddc32f0a3da9f
