### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by slavk0** [Farata/EnterpriseWebBook#44]
"Flexdevelopers" in the Summary right below "Should we develop in HTML5 if its standard is not finalized yet?" section.

**Comment by gAmUssA** [comment]
Hi,
Could you submit pull request?

Thanks

**Comment by slavk0** [comment]
Sure, there you go.

**Comment by slavk0** [comment]
Hi Victor, I kept reading the book yesterday and found several more typos and quite a few grammatical errors, but I assume those are going to be taken care of later in the process, so there's no need to submit any pull requests at this point, right? Great job on the book btw, I'm really enjoying it.

**Comment by gAmUssA** [comment]
Hi @slavk0,
Yes, those typos will go away later. But if you have time to submit them, it would be great.
Thanks
