### ISSUE TITLE
How to test PHP server without Apache

### ISSUE THREAD

**Issue by bonm** [Farata/EnterpriseWebBook#68]
![php1](https://f.cloud.github.com/assets/3770296/1042115/b7df4068-0fe4-11e3-939e-dd6e7909fa20.PNG)

1) Check version, if  PHP version 5.4.0 or hi  you can use a built-in web server
![php2](https://f.cloud.github.com/assets/3770296/1042145/3f5393e6-0fe5-11e3-8425-b7ac7361fa1a.PNG)

2) You mast set address and port in -S option ,the -t option is used to specify an explicit document root

![php5](https://f.cloud.github.com/assets/3770296/1042117/b81128bc-0fe4-11e3-8e21-c06606f4bef8.PNG)
3) afte start the terminal will show

![php6](https://f.cloud.github.com/assets/3770296/1042118/b8184584-0fe4-11e3-8ac6-259ef13346d8.PNG)

![php7](https://f.cloud.github.com/assets/3770296/1042468/55a5cf5e-0fec-11e3-9696-9dad251948b2.PNG)

4) terminal will show all request form web browser

This web server is designed for developmental purposes only, and should not be used in production.

**Comment by gAmUssA** [comment]
Moved to wiki page https://github.com/Farata/EnterpriseWebBook/wiki/How-to-run-examples-with-build-in-PHP-server-(without-Apache-httpd)
