### ISSUE TITLE
Question about variable name business

### ISSUE THREAD

**Issue by bonm** [Farata/EnterpriseWebBook#81]
In  chapter 5 [ch5_jquery submitting-donate-form](https://github.com/Farata/EnterpriseWebBook/blob/master/ch5_jquery.asciidoc#submitting-donate-form).

We have      input variable name is "business", 

![1q](https://f.cloud.github.com/assets/3770296/1155701/609328d8-1f75-11e3-88f5-02dd41eb866c.png)
## ![2q](https://f.cloud.github.com/assets/3770296/1155700/60937f68-1f75-11e3-964f-f7e17d8bc2ec.png)

but in **php** script we are catch 
$_POST['paypal_email']

![3q](https://f.cloud.github.com/assets/3770296/1155702/6098975a-1f75-11e3-9488-e5e9c522cf8f.png)
![4q](https://f.cloud.github.com/assets/3770296/1155703/609bcca4-1f75-11e3-978d-011aa3b6b280.png)

is that correct?

**Comment by yfain** [comment]
Thanks, good catch! 

 The name="business" should be replaced with name="paypal_email". Will do it shortly.
